-- Zodiac Signs table with detailed information
CREATE TABLE IF NOT EXISTS zodiac_signs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sign VARCHAR(20) NOT NULL UNIQUE,
    name_tr VARCHAR(50) NOT NULL,
    name_en VARCHAR(50) NOT NULL,
    element VARCHAR(20) NOT NULL,
    quality VARCHAR(20) NOT NULL,
    ruling_planet VARCHAR(30) NOT NULL,
    lucky_numbers JSON,
    lucky_colors JSON,
    compatible_signs JSON,
    date_range_start VARCHAR(10) NOT NULL,
    date_range_end VARCHAR(10) NOT NULL,
    symbol VARCHAR(10) NOT NULL,
    description TEXT,
    traits JSON,
    strengths JSON,
    weaknesses JSON,
    career_suggestions JSON,
    love_compatibility JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Insert zodiac signs data
INSERT INTO zodiac_signs (sign, name_tr, name_en, element, quality, ruling_planet, 
    lucky_numbers, lucky_colors, compatible_signs, date_range_start, date_range_end, 
    symbol, description, traits, strengths, weaknesses) VALUES
('koc', 'Koç', 'Aries', 'Ateş', 'Öncü', 'Mars', 
    '[1, 8, 15]', '["Kırmızı", "Turuncu"]', '["aslan", "yay"]', 
    '03-21', '04-19', '♈', 
    'Enerjik ve cesur doğal liderler', 
    '["cesur", "enerjik", "bağımsız", "rekabetçi"]',
    '["liderlik", "cesaret", "başlangıç yapma"]',
    '["sabırsızlık", "agresiflik", "inatçılık"]'),
('boga', 'Boğa', 'Taurus', 'Toprak', 'Sabit', 'Venüs',
    '[2, 6, 9, 12, 24]', '["Yeşil", "Pembe"]', '["basak", "oglak"]',
    '04-20', '05-20', '♉',
    'Güvenilir ve kararlı, güzelliği seven',
    '["kararlı", "güvenilir", "sabırlı", "pratik"]',
    '["sadakat", "kararlılık", "estetik anlayış"]',
    '["inatçılık", "değişime direnç", "kıskançlık"]'),
('ikizler', 'İkizler', 'Gemini', 'Hava', 'Değişken', 'Merkür',
    '[5, 7, 14, 23]', '["Sarı", "Gümüş"]', '["terazi", "kova"]',
    '05-21', '06-20', '♊',
    'Meraklı ve adaptasyonu yüksek iletişimciler',
    '["meraklı", "akıllı", "sosyal", "uyumlu"]',
    '["iletişim", "adaptasyon", "öğrenme"]',
    '["kararsızlık", "yüzeysellik", "huzursuzluk"]'),
('yengec', 'Yengeç', 'Cancer', 'Su', 'Öncü', 'Ay',
    '[2, 7, 11, 16, 20, 25]', '["Beyaz", "Gümüş", "Mavi"]', '["akrep", "balik"]',
    '06-21', '07-22', '♋',
    'Duygusal ve koruyucu, aile odaklı',
    '["duygusal", "koruyucu", "sezgisel", "şefkatli"]',
    '["empati", "sadakat", "koruma"]',
    '["aşırı duyarlılık", "kabuğuna çekilme", "geçmişe bağlılık"]'),
('aslan', 'Aslan', 'Leo', 'Ateş', 'Sabit', 'Güneş',
    '[1, 3, 10, 19]', '["Altın", "Turuncu", "Sarı"]', '["koc", "yay"]',
    '07-23', '08-22', '♌',
    'Gururlu ve cömert, doğal performansçılar',
    '["gururlu", "cömert", "yaratıcı", "dramatik"]',
    '["liderlik", "yaratıcılık", "cömertlik"]',
    '["kibirlilik", "ego", "dikkat arayışı"]'),
('basak', 'Başak', 'Virgo', 'Toprak', 'Değişken', 'Merkür',
    '[6, 14, 18, 29]', '["Lacivert", "Gri", "Bej"]', '["boga", "oglak"]',
    '08-23', '09-22', '♍',
    'Analitik ve mükemmeliyetçi, detaycı',
    '["analitik", "mükemmeliyetçi", "pratik", "hizmet odaklı"]',
    '["analiz", "organizasyon", "problem çözme"]',
    '["aşırı eleştiri", "endişe", "mükemmeliyetçilik"]'),
('terazi', 'Terazi', 'Libra', 'Hava', 'Öncü', 'Venüs',
    '[4, 6, 13, 15, 24]', '["Mavi", "Pastel renkler"]', '["ikizler", "kova"]',
    '09-23', '10-22', '♎',
    'Adaletli ve dengeli, uyum arayan',
    '["adaletli", "diplomatik", "estetik", "sosyal"]',
    '["denge", "adalet", "estetik anlayış"]',
    '["kararsızlık", "çatışmadan kaçma", "bağımlılık"]'),
('akrep', 'Akrep', 'Scorpio', 'Su', 'Sabit', 'Plüton',
    '[4, 13, 18, 22]', '["Bordo", "Siyah", "Koyu kırmızı"]', '["yengec", "balik"]',
    '10-23', '11-21', '♏',
    'Yoğun ve gizemli, dönüşüm gücü',
    '["yoğun", "gizemli", "kararlı", "sezgisel"]',
    '["dönüşüm", "araştırma", "sadakat"]',
    '["kıskançlık", "intikamcılık", "obsesyon"]'),
('yay', 'Yay', 'Sagittarius', 'Ateş', 'Değişken', 'Jüpiter',
    '[3, 9, 15, 21, 27]', '["Mor", "Turkuaz"]', '["koc", "aslan"]',
    '11-22', '12-21', '♐',
    'Özgür ruhlu ve felsefik, macera seven',
    '["özgür", "iyimser", "felsefik", "maceraperest"]',
    '["özgürlük", "öğretme", "keşfetme"]',
    '["sorumsuzluk", "sabırsızlık", "taktiksilik"]'),
('oglak', 'Oğlak', 'Capricorn', 'Toprak', 'Öncü', 'Satürn',
    '[6, 8, 13, 21]', '["Siyah", "Koyu yeşil", "Kahverengi"]', '["boga", "basak"]',
    '12-22', '01-19', '♑',
    'Disiplinli ve hırslı, başarı odaklı',
    '["disiplinli", "hırslı", "pratik", "sorumlu"]',
    '["disiplin", "liderlik", "sorumluluk"]',
    '["katılık", "karamsarlık", "aşırı ciddiyet"]'),
('kova', 'Kova', 'Aquarius', 'Hava', 'Sabit', 'Uranüs',
    '[4, 7, 11, 22, 29]', '["Mavi", "Gümüş", "Elektrik mavisi"]', '["ikizler", "terazi"]',
    '01-20', '02-18', '♒',
    'Yenilikçi ve bağımsız, humanist',
    '["yenilikçi", "bağımsız", "humanist", "orijinal"]',
    '["yenilik", "bağımsızlık", "humanitarian"]',
    '["aloof", "inatçılık", "aşırı idealizm"]'),
('balik', 'Balık', 'Pisces', 'Su', 'Değişken', 'Neptün',
    '[3, 9, 12, 15, 18, 24]', '["Deniz yeşili", "Mor", "Gümüş"]', '["yengec", "akrep"]',
    '02-19', '03-20', '♓',
    'Sezgisel ve empatik, hayal gücü kuvvetli',
    '["sezgisel", "empatik", "yaratıcı", "şefkatli"]',
    '["empati", "yaratıcılık", "spiritüellik"]',
    '["kaçışçılık", "aşırı duyarlılık", "kararsızlık"]');

-- Indexes
CREATE INDEX idx_zodiac_sign ON zodiac_signs(sign);
CREATE INDEX idx_zodiac_element ON zodiac_signs(element);